### ISSUE TITLE
cannot import name 'clock' from 'time' 

### ISSUE THREAD

**Issue by davidlinhl** [AequilibraE/aequilibrae#100]
I am running QGIS 3.10 on manjaro linux with python 3.8. After installing the plugin I get a error while opening it saying

> ImportError: cannot import name 'clock' from 'time' (unknown location)

Here are the details:

Couldn't load plugin 'AequilibraE' due to an error when calling its classFactory() method 

ImportError: cannot import name 'clock' from 'time' (unknown location) 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/lin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/AequilibraE/__init__.py", line 32, in classFactory
    from .AequilibraEMenu import AequilibraEMenu
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/lin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/AequilibraE/AequilibraEMenu.py", line 52, in 
    from .distribution_procedures import DistributionModelsDialog
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/lin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/AequilibraE/distribution_procedures/__init__.py", line 21, in 
    from .distribution_models_dialog import DistributionModelsDialog
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/lin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/AequilibraE/distribution_procedures/distribution_models_dialog.py", line 37, in 
    from aequilibrae.distribution import SyntheticGravityModel
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/lin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/AequilibraE/aequilibrae/aequilibrae/distribution/__init__.py", line 15, in 
    from .ipf import Ipf
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/lin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/AequilibraE/aequilibrae/aequilibrae/distribution/ipf.py", line 23, in 
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)

Python version: 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0] 
QGIS version: 3.10.1-A Coruña A Coruña, exported 

Python Path:
/home/lin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/AequilibraE/aequilibrae
/home/lin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/AequilibraE/aequilibrae
/home/lin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/networks
/usr/share/qgis/python
/home/lin/.local/share/QGIS/QGIS3/profiles/default/python
/home/lin/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/lin/.local/lib/python3.8/site-packages
/usr/lib/python3.8/site-packages
/home/lin/.local/share/QGIS/QGIS3/profiles/default/python
/home/lin/Desktop

After my research it seems time.clock() was deprecated in python3.3 and finally removed in python3.8.
Maybe consider switching to other timing methods

**Comment by pedrocamargo** [comment]
@davidlinhl , This bug is for the QGIS plugin.  Can you report it on the plugin's repo?

https://github.com/AequilibraE/AequilibraE-GUI/issues

There will be a new version that will also solve this issue within the next week.

**Comment by pedrocamargo** [comment]
But in any case, it is fixed already.  Will be available in the next release.

**Comment by davidlinhl** [comment]
Sorry I didn't realiae thr difference. Also happy that this is solved.

**Comment by pedrocamargo** [comment]
@davidlinhl , There is a new version available on PyPi that fixes the issue you are having. The QGIS version will be release in the next 48h
