### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by ebin-sam** [AequilibraE/aequilibrae#252]
I got the following error while installing the plugin. Please look into it.

Couldn't load plugin 'AequilibraE' due to an error when calling its classFactory() method 

ImportError: DLL load failed: The specified module could not be found.

**Comment by pedrocamargo** [comment]
@ebin-sam , A few issues with your bug report.

1. It is related to the plugin, and this is the repository for the Python library.
2. You have not provided any detail on your issue, which makes it impossible to even determine if that is a plugin bug, an issue with your system, or if you have made a mistake.  

The templates are provided for a reason.

**Comment by ebin-sam** [comment]
Couldn't load plugin 'AequilibraE' due to an error when calling its classFactory() method 

ImportError: DLL load failed: The specified module could not be found. 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AequilibraE\__init__.py", line 32, in classFactory
    from .AequilibraEMenu import AequilibraEMenu
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AequilibraE\AequilibraEMenu.py", line 24, in 
    from .common_tools import ParameterDialog, GetOutputFileName, LogDialog
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AequilibraE\common_tools\__init__.py", line 5, in 
    from .load_graph_layer_setting_dialog import LoadGraphLayerSettingDialog
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AequilibraE\common_tools\load_graph_layer_setting_dialog.py", line 33, in 
    from aequilibrae.project import Project
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae\aequilibrae\__init__.py", line 3, in 
    from aequilibrae import distribution
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae\aequilibrae\distribution\__init__.py", line 1, in 
    from .ipf import Ipf
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae\aequilibrae\distribution\ipf.py", line 26, in 
    from ..matrix import AequilibraeData
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae\aequilibrae\matrix\__init__.py", line 1, in 
    from .aequilibrae_matrix import AequilibraeMatrix, matrix_export_types
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae\aequilibrae\matrix\aequilibrae_matrix.py", line 16, in 
    import openmatrix as omx
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\openmatrix\__init__.py", line 3, in 
    import tables
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tables\__init__.py", line 99, in 
    from .utilsextension import (
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: The specified module could not be found.


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.5-Hannover Hannover, 58ba7c1ed6 

Python Path:
C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae
C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae
C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae
C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\clusterpoints
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\Users\user\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.

**Comment by pedrocamargo** [comment]
@ebin-sam , You still have not read the instructions when filing a bug report OR read my previous message. Throwing the stack trace here helps very little.

**Comment by pedrocamargo** [comment]
@ebin-sam , e-mailing me directly to solve your problems is not an acceptable behaviour. Please follow the instructions provided in when filling issues or asking questions
