### ISSUE TITLE
Not possible to save skims from multi-class assignment

### ISSUE THREAD

**Issue by pedrocamargo** [AequilibraE/aequilibrae#298]
**Purpose of use**
Multi-class traffic assignment

**Describe the bug**
The software crashes when trying to save skims from multiple classes during multi-class traffic assignment

**To Reproduce**
1. Run a multi-class assignment for skimming for more than one class
2. Call `assig.save_skims('matrix_name')` after executing the assignment

**Expected behavior**
Saving a single skim matrix for all modes

**Screenshots**

`D:\src\aequilibrae\aequilibrae\parameters.py:53: UserWarning: No pre-existing parameter file exists for this project. Will use default
  warn('No pre-existing parameter file exists for this project. Will use default')
2022-03-21 16:32:44,645;Matrix Record has been saved to the database
Traceback (most recent call last):
  File "D:/release/Sample models/sioux_falls_multi-Class/SiouxFalls MC.py", line 86, in <module>
    assig.save_skims(scenario)
  File "D:\src\aequilibrae\aequilibrae\paths\traffic_assignment.py", line 638, in save_skims
    record = mats.new_record(matrix_name, file_name)
  File "D:\src\aequilibrae\aequilibrae\project\data\matrices.py", line 157, in new_record
    raise ValueError(f"There is already a matrix of name ({name}). It must be unique.")
ValueError: There is already a matrix of name (84bdfbf063754b5b9e555a02fea9f88a). It must be unique.
`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.8
 - Develop Branch

**Comment by pedrocamargo** [comment]
The solution given to this problem is to create a skim matrix per traffic classed assigned
