### ISSUE TITLE
Cannot compute shortest path

### ISSUE THREAD

**Issue by Art-Ev** [AequilibraE/aequilibrae#307]
**Describe the bug**

Traceback (most recent call last):
              File "%FolderProfile%/python/plugins\AequilibraE\paths_procedures\show_shortest_path_dialog.py", line 154, in produces_path
              self.res.compute_path(int(self.path_from.text()), int(self.path_to.text()))
              File "%FolderProfile%\python\plugins\AequilibraE\aequilibrae\aequilibrae\paths\results\path_results.py", line 88, in compute_path
              self.skims[self.graph.all_nodes, :] = self._skimming_array[:-1, :]
             IndexError: index 1066 is out of bounds for axis 0 with size 1066

**To Reproduce**
Use shortest path dialog: 
For example trying to find shortest (distance) path from 387 to 1067 with [St_Varent.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/8462386/St_Varent.zip)

**Desktop (please complete the following information):**
 - OS: windows 10
 - QGIS Version 3.22

**Comment by pedrocamargo** [comment]
@Art-Ev , I will close this issue as it has already been merged into develop and that's the workflow we are using for AequilibraE now
